### ISSUE TITLE
Reward rate undefined causing app to not load

### ISSUE THREAD

**Issue by gjj** [BirthdayResearch/uniswap.defichain.com#99]
#### What happened:

Sometimes, when clicking the `back arrow` from the `Add Liquidity` page back to the `Pool` page, will see this error. Should be fixed asap as it's an unhappy path for users.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/506667/184171714-d281b4ee-ee36-44af-af5a-a289e1deaf49.png">

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/506667/184171170-5a122ee9-fd9e-47c8-bdb0-9c1cd2463ba7.png">

#### What you expected to happen:

It should go back to the `Pool` page with no errors. Might be because of the non-null assertions. 

#### How to reproduce it (as minimally and precisely as possible):

Seemingly random for now.

**Comment by gjj** [comment]
@Abhishekkochar need to handle the case where the `reward rates` are undefined.

![image](https://user-images.githubusercontent.com/506667/184171915-0a56c613-2626-412c-9f61-33e410b0e0d5.png)

**Comment by Abhishekkochar** [comment]
@gjj, I saw it early in the morning. Worked on it as well. Realised you already requested a review. Thanks for sussing this out.
